apiVersion: v1
kind: Secret
metadata:
  name: scylla-cdc-{{ .Release.Name }}
type: Opaque
data:
  SCYLLA_PROD_HOST: {{ .Values.scyllaDBConfig.host | b64enc | quote }}
  SCYLLA_PROD_PORT: {{ .Values.scyllaDBConfig.port | b64enc | quote }}
  SCYLLA_PROD_USERNAME: {{ .Values.scyllaDBConfig.userName | b64enc | quote }}
  SCYLLA_PROD_PASSWORD: {{ .Values.scyllaDBConfig.scPassword | b64enc | quote }}
  KAFKA_ENDPOINT_WITH_PORT: {{ .Values.kafkaBrokers  | b64enc | quote }}
  MYSQL_HOST_SYCLLA_CONNECTOR: {{ .Values.dataSourceConfig.jdbcUrl | b64enc | quote }}
  MYSQL_USR: {{ .Values.dataSourceConfig.username | b64enc | quote }}
  MYSQL_PWD: {{ .Values.dataSourceConfig.password | b64enc | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.slackWebhookURL | b64enc | quote }}
  DATA_CENTER: {{ .Values.dcName | b64enc | quote }}